// <auto-generated />
namespace TenantOrganiser.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FacebookUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FacebookUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201404161447240_FacebookUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
